### ISSUE TITLE
Add a "go to tick" RCON command in the "play" window

### ISSUE THREAD

**Issue by Azsofe** [Square789/Demomgr#30]
Somenthing like this. Or maybe add it as a launch option, but I'm not sure if it will work
![RCON](https://user-images.githubusercontent.com/44698264/126459372-033031a4-cd7e-4bdf-b01e-0a7edb2a90e1.jpeg)

**Comment by Square789** [comment]
Thanks for the suggestion; the command `demo_gototick` is settable as an additional launch arg and should also be sendable through RCON, I'll look into it!

**Comment by Square789** [comment]
Seems stable since 15e59d9e898dc4ff51d820361f1d512d34605336, should've probably closed this back then, sorry
