### ISSUE TITLE
Can't load a demo using HLAE

### ISSUE THREAD

**Issue by Azsofe** [Square789/Demomgr#46]
Since the TF2 x64 update, the file name for the executable has changed, and I guess that demomgr is sending wrong parameters to HLAE.
As of now, HLAE does not support x64, so we must use the legacy version (tf.exe)
Could you please look into this ?

HLAE Error message after clicking on "Launch TF2":
AfxError #2002: 
Title: Loader could not create requested process.
Description: GetLastWin32Error = 2: The specified file can not be found
Solution: Make sure you entered the correct path to the game .exe and included the .exe file. Copy the path from the game properties in Steam to make sure you are using the correct path.

**Comment by Square789** [comment]
@Azsofe Should be working again with the 1.11.0 release, if you could share your results with it, that'd be great!

**Comment by Azsofe** [comment]
Perfect ! As expected, when I try to use x64 with HLAE it doesn't work, and it falls back to vanilla tf2. That's great ! Thank you !
